name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Нужно для корректной работы фильтров Turbo

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma
        run: pnpm gen:db
        env:
          DATABASE_URL: "postgresql://postgres:password@localhost:5432/test_db"

      - name: Run CI tasks
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            pnpm turbo run build lint check-types --filter="...[origin/main]"
          else
            pnpm turbo run build lint check-types --filter="...[${{ github.event.before }}...${{ github.sha }}]"
          fi
        env:
          DATABASE_URL: "postgresql://postgres:password@localhost:5432/test_db"